{{- if .Values.licenseMaster.enabled }}
apiVersion: enterprise.splunk.com/v3
kind: LicenseMaster
metadata:
  name: licensemaster
spec:
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
{{- end }}
