{{- if .Values.indexerCluster.enabled }}
apiVersion: enterprise.splunk.com/v3
kind: IndexerCluster
metadata:
  name: indexercluster
spec:
  replicas: {{ .Values.indexerCluster.replicaCount }}
  clusterMasterRef: {{ .Values.clusterMaster.name }}
{{- end }}
