{{- if .Values.splunkOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-enterprise-stack.operator.serviceAccountName" . }}
  namespace: {{ include "splunk-enterprise-stack.namespace" . }}
  labels:
    {{- include "splunk-enterprise-stack.labels" . | nindent 4 }}
{{- end }}

