{{- if or .Values.indexerCluster.enabled .Values.sva.c3.enabled .Values.sva.m4.enabled }}
apiVersion: v1
kind: List
items:
{{- range default (default (until 1) .Values.sva.c3.indexerClusters) .Values.sva.m4.indexerClusters }}
- apiVersion: enterprise.splunk.com/v3
  kind: IndexerCluster
  metadata:
  {{- if or $.Values.sva.c3.enabled $.Values.sva.m4.enabled }}
    name: {{ .name }}
  {{- else if $.Values.indexerCluster.enabled }}
    name: {{ $.Values.indexerCluster.name }}
  {{- end }}
    namespace: {{ default $.Release.Namespace $.Values.indexerCluster.namespaceOverride }}
  {{- with $.Values.indexerCluster.additionalLabels }}
    labels:
{{ toYaml . | indent 6 }}
  {{- end }}
  spec:
  {{- if $.Values.indexerCluster.replicaCount }}
    replicas: {{ $.Values.indexerCluster.replicaCount }}
  {{- end }}
  {{- if $.Values.existingClusterMaster }}
    clusterMasterRef:
      name: {{ $.Values.existingClusterMaster.name }}
    {{- if $.Values.existingClusterMaster.namespace }}
      namespace: {{ $.Values.existingClusterMaster.namespace }}
    {{- end }}
  {{- else if or $.Values.clusterMaster.enabled $.Values.sva.c3.enabled $.Values.sva.m4.enabled }}
    clusterMasterRef:
      name: {{ $.Values.clusterMaster.name }}
    {{- if $.Values.clusterMaster.namespaceOverride }}
      namespace: {{ $.Values.clusterMaster.namespaceOverride }}
    {{- end }}
  {{- end }}
  {{- if $.Values.existingLicenseMaster }}
    licenseMasterRef:
      name: {{ $.Values.existingLicenseMaster.name }}
    {{- if $.Values.existingLicenseMaster.namespace }}
      namespace: {{ $.Values.existingLicenseMaster.namespace }}
    {{- end }}
  {{- else if $.Values.licenseMaster.enabled }}
    licenseMasterRef:
      name: {{ $.Values.licenseMaster.name }}
    {{- if $.Values.licenseMaster.namespaceOverride }}
      namespace: {{ $.Values.licenseMaster.namespaceOverride }}
    {{- end }}
  {{- end }}
  {{- if $.Values.existingMonitoringConsole }}
    monitoringConsoleRef:
      name: {{ $.Values.existingMonitoringConsole.name }}
    {{- if $.Values.existingMonitoringConsole.namespace }}
      namespace: {{ $.Values.existingMonitoringConsole.namespace }}
    {{- end }}
  {{- else if $.Values.monitoringConsole.enabled }}
    monitoringConsoleRef:
      name: {{ $.Values.monitoringConsole.name }}
    {{- if $.Values.monitoringConsole.namespaceOverride }}
      namespace: {{ $.Values.monitoringConsole.namespaceOverride }}
    {{- end }}
  {{- end }}
  {{- if $.Values.image.repository }}
    image: {{ $.Values.image.repository }}
  {{- end }}
  {{- if $.Values.image.imagePullPolicy }}
    imagePullPolicy: {{ $.Values.image.imagePullPolicy }}
  {{- end }}
  {{- with $.Values.image.imagePullSecrets }}
    imagePullSecrets:
{{ toYaml . | indent 6 }}
  {{- end }}
  {{- with $.Values.indexerCluster.volumes }}      
    volumes:
{{ toYaml . | indent 6 }}
  {{- end }}
  {{- if $.Values.indexerCluster.licenseUrl }}
    licenseUrl: {{ $.Values.indexerCluster.licenseUrl }}
  {{- end }}
  {{- if $.Values.indexerCluster.defaultsUrl }}
    defaultsUrl: {{ $.Values.indexerCluster.defaultsUrl }}
  {{- end }}
  {{- if $.Values.sva.m4.enabled }}
    {{- $cm_name := $.Values.clusterMaster.name -}}
    {{- if $.Values.existingClusterMaster }}
      {{- $cm_name = $.Values.existingClusterMaster.name -}}
    {{- end }}
    defaults: |-
      splunk:
        multisite_master: splunk-{{ $cm_name }}-cluster-master-service
        site: {{ .site }}
  {{- else if $.Values.indexerCluster.defaults }}
    defaults: |-
{{ toYaml $.Values.indexerCluster.defaults | indent 6 }}
  {{- end }}
  {{- with $.Values.indexerCluster.extraEnv }}
    extraEnv:
{{ toYaml . | indent 6 }}
  {{- end }}
  {{- if $.Values.indexerCluster.livenessInitialDelaySeconds }}
    livenessInitialDelaySeconds: {{ $.Values.indexerCluster.livenessInitialDelaySeconds }}
  {{- end }}
  {{- if $.Values.indexerCluster.readinessInitialDelaySeconds }}
    readinessInitialDelaySeconds: {{ $.Values.indexerCluster.readinessInitialDelaySeconds }}
  {{- end }}
  {{- with $.Values.indexerCluster.etcVolumeStorageConfig }}
    etcVolumeStorageConfig:
{{ toYaml . | indent 6 }}
  {{- end }}
  {{- with $.Values.indexerCluster.varVolumeStorageConfig }}
    varVolumeStorageConfig:
{{ toYaml . | indent 6 }}
  {{- end }}
  {{- with $.Values.indexerCluster.resources }}
    resources:
{{ toYaml . | indent 6 }}
  {{- end }}
  {{- if $.Values.indexerCluster.serviceAccount }}
    serviceAccount: {{ $.Values.indexerCluster.serviceAccount }}
  {{- end }}
  {{- with $.Values.indexerCluster.tolerations }}
    tolerations:
{{ toYaml . | indent 6 }}
  {{- end }}
  {{- if $.Values.sva.m4.enabled }}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
              - {{ .zone }}
  {{- else }}
    {{- with $.Values.indexerCluster.affinity }}
    affinity:
{{ toYaml . | indent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}